
services:
  db:  
    image: mysql:8.0
    command: 
      - --default-authentication-plugin=mysql_native_password          
      - --skip-name-resolve  # Critical for faster connections
      - --bind-address=0.0.0.0  # Allow all connections
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: ksdb
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin@123
    container_name : ksdbs  
    networks:
      mynet:
        ipv4_address: 172.20.0.100  
    volumes:
      - ./init-scripts:/docker-entrypoint-initdb.d  # Mount initialization scripts
      - mysql_data:/var/lib/mysql  # Persistent data
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-uroot", "-prootpass"]
      interval: 5s
      timeout: 5s
      retries: 15

  service1:
    build :
      context: ./Docker-file/service1
    image: kartikeyadhub/ksservice1
    container_name : ksservice1
    ports :
      - "9001:9001"



volumes:
  mysql_data:

networks:
  mynet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
          gateway: 172.20.0.1